### ISSUE TITLE
libdbus-1-dev required

### ISSUE THREAD

**Issue by kineticz** [frewsxcv/alert-after#13]
On ubuntu 16.04 I need to `sudo apt install libdbus-1-dev`, otherwise I got a `dbus-1 not found` error.

Perhaps add some instructions on the readme?

Thanks for the nice tool!

**Comment by frewsxcv** [comment]
It's mentioned in the 'Install' section in the README:

https://github.com/frewsxcv/alert-after#install

**Comment by kineticz** [comment]
Ah, my bad.

**Comment by frewsxcv** [comment]
No worries!
