### ISSUE TITLE
Doesn't work on windows 8.1

### ISSUE THREAD

**Issue by Boscop** [frewsxcv/alert-after#19]
I don't get any notification bubble :(

**Comment by Boscop** [comment]
Is there a chance that it could work with this?
https://github.com/allenbenz/winrt-notification

**Comment by frewsxcv** [comment]
If you find a way to make it work, feel free to open a PR. I don't have a windows machine to test on so Im not going to be much help. It might be worth fixing this upstream in the notification crate alert-after relies on
