### ISSUE TITLE
Turn this into a library

### ISSUE THREAD

**Issue by zoidyzoidzoid** [frewsxcv/alert-after#21]
Hi there, this is a great library, and I've been using some of the code for a CLI tool of mine, since [notify-rust](https://github.com/hoodie/notify-rust)'s support for MacOS isn't great.

Would you be keen to see a contribution that makes the notification code in this tool more reusable?

**Comment by frewsxcv** [comment]
Good idea! I'm pretty short on time but if some else wants to do this, feel free to take any of this code. If a new library gets created, I'll remove all the system notification code from alert-after and  add a dependency for that new library

**Comment by hayd** [comment]
This would be really nice as a library (which just exports a `fn notify(msg_title: &str, msg_body: &str)` function).

Would you accept a PR that refactors to use lib.rs and main.rs? Or does this need to be a new repo?

**Comment by frewsxcv** [comment]
created a new crate here: https://github.com/frewsxcv/rust-notifica

and migrated alert-after to use it here: https://github.com/frewsxcv/alert-after/commit/c987388f226e164b86f4adeabf3c9698b0b1d3fd
