### ISSUE TITLE
Installation Issue 

### ISSUE THREAD

**Issue by giatrakosg** [frewsxcv/alert-after#6]
After install rust and runing the command
   $cargo install alert-after 
I get the following error 
![image](https://cloud.githubusercontent.com/assets/22731222/24582938/59fec232-1744-11e7-8ced-4929cec87414.png)

 I am running linux / elementary OS - loki

**Comment by frewsxcv** [comment]
I think you'll need to upgrade your Rust to the latest stable version. I don't know which version added support for platform specific dependencies in Cargo.toml.

**Comment by frewsxcv** [comment]
@giatrakosg Did you happen to get this working?

**Comment by giatrakosg** [comment]
Hi ,
 yes my issue was resolved.I am sorry for the late reply it was 1pm when I found it.

Good Luck with your project!
